name: Create lib-version Pre-release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build-and-publish:
    name: Build & Create GitHub Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code at the tagged commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools-scm>=6.2

      - name: Build package
        run: python -m build --sdist --wheel .

      - name: Create GitHub Pre-release with Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Pre-release lib-version ${{ github.ref_name }}
          body: "Automated pre-release of the lib-version Python package."
          prerelease: true
          files: dist/*
