name: Verify and Pre-release lib-version

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' 

jobs:
  build-verify-prerelease:
    name: Build, Verify, and Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine trigger type
        id: trigger
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "triggered_by=tag" >> $GITHUB_OUTPUT
          else
            echo "triggered_by=branch" >> $GITHUB_OUTPUT
          fi

      - name: Get latest stable tag
        run: |
          if [[ "${{ steps.trigger.outputs.triggered_by }}" == "branch" ]]; then
            LATEST=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          else
            LATEST="${{ github.ref_name }}"
          fi
          echo "LATEST_TAG=$LATEST" >> $GITHUB_ENV

      - name: Calculate prerelease version
        run: |
          BASE=${LATEST_TAG#v}
          BASE=${BASE%%-pre*}
          IFS=. read MAJOR MINOR PATCH <<< "$BASE"
          PATCH=$((PATCH + 1))
          TS=$(date +%Y%m%d%H%M%S)
          PREVER="v${MAJOR}.${MINOR}.${PATCH}.dev${TS}"
          echo "PRERELEASE_TAG=$PRE"    >> $GITHUB_ENV
          echo "MAJOR=$MAJOR"           >> $GITHUB_ENV
          echo "MINOR=$MINOR"           >> $GITHUB_ENV
          echo "PATCH=$PATCH"           >> $GITHUB_ENV

      - name: Tag prerelease commit
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          if [[ "${{ steps.trigger.outputs.triggered_by }}" == "branch" ]]; then
            SHA=$(git rev-parse origin/main)
          else
            SHA="${{ github.sha }}"
          fi
          git tag "${{ env.PRERELEASE_TAG }}" $SHA
          git push origin "${{ env.PRERELEASE_TAG }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build & test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest twine wheel setuptools-scm>=6.2

      - name: Build package
        run: python -m build

      - name: Install package and run tests
        run: |
          pip install dist/*.whl
          pytest

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: lib-version-dist
          path: dist/

      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.PRERELEASE_TAG }}
          name: Pre-release ${{ env.PRERELEASE_TAG }}
          prerelease: true
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
