name: Verify and Pre-release lib-version

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+(?:\.[0-9]+){2}*'  

jobs:
  build-verify-prerelease:
    name: Build, Verify, and Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write    # for pushing tags & creating the release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Determine trigger type
        id: trigger
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "by_tag=true"  >> $GITHUB_OUTPUT
          else
            echo "by_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Calculate prerelease version
        run: |
          # 1) pick latest stable tag or the pushed tag
          if [ "${{ steps.trigger.outputs.by_tag }}" = "true" ]; then
            LATEST="${{ github.ref_name }}"
          else
            LATEST=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          fi

          # 2) strip leading "v" and any "-pre" or ".dev"
          BASE=${LATEST#v}
          BASE=${BASE%%[-.+]*}

          IFS=. read MAJOR MINOR PATCH <<<"$BASE"

          # 3) bump patch and add a PEP-440 dev suffix
          PATCH=$((PATCH + 1))
          TS=$(date +%Y%m%d%H%M%S)
          PRERELEASE_TAG="v${MAJOR}.${MINOR}.${PATCH}.dev${TS}"

          echo "PRERELEASE_TAG=$PRERELEASE_TAG" >> $GITHUB_ENV

      - name: Tag main commit with prerelease
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # always tag the tip of main
          git fetch origin main
          SHA=$(git rev-parse origin/main)

          git tag "${{ env.PRERELEASE_TAG }}" $SHA
          git push origin "${{ env.PRERELEASE_TAG }}"

      - name: Install build & test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest twine wheel setuptools-scm>=6.2

      - name: Build package
        run: python -m build

      - name: Install package and run tests
        run: |
          pip install dist/*.whl
          pytest

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: lib-version-dist
          path: dist/

      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.PRERELEASE_TAG }}
          name: Pre-release ${{ env.PRERELEASE_TAG }}
          draft: false
          prerelease: true
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
