name: Release lib-version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    name: Build and Create Stable Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code at tagged commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest wheel setuptools-scm>=6.2

      - name: Build package
        run: python -m build --sdist --wheel .

      - name: Install package and run tests
        run: |
          echo "Installing built wheel from dist/..."
          pip install dist/*.whl
          echo "Running tests against installed package..."
          pytest

      - name: Create Stable GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: false
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
